name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  release:
    needs: tests # Only release if passing tests
    uses: ./.github/workflows/release.yml

  publish:
    needs: tests # Only release if passing tests
    uses: ./.github/workflows/publish.yml