name: Prod Release

on:
  workflow_call:

permissions: 
  # Needed to create PR statuses/checks
  checks: write
  statuses: write
  # Needed to push git tags, release
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --unshallow --tags

      - name: Install Auto
        run: |
          npm install -g auto

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          npx auto shipit
